# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : Libri2mix
# ################################
#
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# e.g. '/yourpath/Libri2Mix/train-clean-360/'
# the data folder is needed even if dynamic mixing is applied
data_folder: /scratch/jiaqi006/others/LibriMix/Libri2Mix

# this is the base folder for dynamic mixing
base_folder_dm: /yourpath/LibriSpeech/train-clean-360/

experiment_name: codecformer4/DAC_ss3-512_libritts_L1nq
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save
train_data: !ref <save_folder>/libri2mix_train-360.csv
valid_data: !ref <save_folder>/libri2mix_dev.csv
test_data: !ref <save_folder>/libri2mix_test.csv
skip_prep: False

ckpt_interval_minutes: 60

# Experiment params
precision: fp16 # bf16, fp16 or fp32 # Set it to True for mixed precision
num_spks: 2
noprogressbar: False
save_audio: True # Save estimated sources on disk
n_audio_to_save: 20
sample_rate: 16000
codec_sample_rate: 16000
quantize_before: false
quantize_after: false

####################### Training Parameters ####################################
N_epochs: 100
batch_size: 5
lr: 0.00015
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: False
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 32000000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: False
use_wham_noise: False

# Parameters for data augmentation
use_wavedrop: False
use_speedperturb: True
use_rand_shift: False
min_shift: -8000
max_shift: 8000

# Speed perturbation
speed_changes: [95, 100, 105]  # List of speed changes for time-stretching

speed_perturb: !new:speechbrain.augment.time_domain.SpeedPerturb
    orig_freq: !ref <sample_rate>
    speeds: !ref <speed_changes>

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq_low: 0  # Min frequency band dropout probability
drop_freq_high: 1  # Max frequency band dropout probability
drop_freq_count_low: 1  # Min number of frequency bands to drop
drop_freq_count_high: 3  # Max number of frequency bands to drop
drop_freq_width: 0.05  # Width of frequency bands to drop

drop_freq: !new:speechbrain.augment.time_domain.DropFreq
    drop_freq_low: !ref <drop_freq_low>
    drop_freq_high: !ref <drop_freq_high>
    drop_freq_count_low: !ref <drop_freq_count_low>
    drop_freq_count_high: !ref <drop_freq_count_high>
    drop_freq_width: !ref <drop_freq_width>

# Time drop: randomly drops a number of temporal chunks.
drop_chunk_count_low: 1  # Min number of audio chunks to drop
drop_chunk_count_high: 5  # Max number of audio chunks to drop
drop_chunk_length_low: 1000  # Min length of audio chunks to drop
drop_chunk_length_high: 2000  # Max length of audio chunks to drop

drop_chunk: !new:speechbrain.augment.time_domain.DropChunk
    drop_length_low: !ref <drop_chunk_length_low>
    drop_length_high: !ref <drop_chunk_length_high>
    drop_count_low: !ref <drop_chunk_count_low>
    drop_count_high: !ref <drop_chunk_count_high>

# loss thresholding -- this thresholds the training loss
threshold_byloss: True
threshold: -30

# Encoder parameters
N_encoder_out: 256
out_channels: 256
kernel_size: 16
kernel_stride: 8
d_ffn: 1024

# Dataloader options
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 0

test_dataloader_opts:
  batch_size: 1
  num_workers: 3

# Specifying the network

# Encoder parameters
codec_channels: 512
block_channels: 512 #1024 #256

# block: !new:speechbrain.lobes.models.passblock.PassBlock
block: !new:speechbrain.lobes.models.dual_path.SBTransformerBlock
  num_layers: 16  #16
  d_model: !ref <block_channels>
  nhead: 8  #1/8
  d_ffn: 1024             #2048?
  dropout: 0.1  #0.0/0.1/0.5
  use_positional_encoding: true
  norm_before: true


dacmodel: !new:speechbrain.lobes.models.codecformer3_espnet.DACWrapper
  input_sample_rate: !ref <sample_rate>
  DAC_model_path: /home/jiaqi006/.cache/huggingface/hub/models--espnet--libritts_dac_16k/snapshots/47d8ae9176d761b64956d3c63a397158a20accdc/exp/codec_train_dac_16k_raw_fs16000
  DAC_sample_rate: !ref <codec_sample_rate>
  Freeze: true
  pth_file_name: 104epoch.pth
  
sepmodel: !new:speechbrain.lobes.models.codecformer4.simpleSeparator3
  num_spks: 2
  channels: !ref <codec_channels>
  block: !ref <block>
  block_channels: !ref <block_channels>

# sepmodel: !new:speechbrain.lobes.models.codecformer3.simpleUNetSeparator
#     num_spks: !ref <num_spks> 
#     channels: !ref <channels>
#     block: !ref <dprnnblock>

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0

#Loss parameters
loss: !name:speechbrain.nnet.losses.get_si_snr_with_pitwrapper
L1_loss: !name:speechbrain.nnet.losses.get_L1_with_pitwrapper

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 2
    dont_halve_until_epoch: 50d

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
  sepmodel: !ref <sepmodel>
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <save_folder>
  recoverables:
    sepmodel: !ref <sepmodel>
    counter: !ref <epoch_counter>
    lr_scheduler: !ref <lr_scheduler>
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# If you do not want to use the pretrained separator you can simply delete pretrained_separator field.
# pretrained_separator: !new:speechbrain.utils.parameter_transfer.Pretrainer
#     collect_in: !ref <save_folder>
#     loadables:
#         encoder: !ref <Encoder>
#         decoder: !ref <Decoder>
#         masknet: !ref <MaskNet>
#     paths:
#         encoder: speechbrain/sepformer-wsj02mix/encoder.ckpt
#         decoder: speechbrain/sepformer-wsj02mix/decoder.ckpt
#         masknet: speechbrain/sepformer-wsj02mix/masknet.ckpt
